services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ez_scheduler
      POSTGRES_USER: ez_user
      POSTGRES_PASSWORD: ez_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ez_user -d ez_scheduler"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://ez_user:ez_password@postgres:5432/ez_scheduler
      REDIS_URL: redis://redis:6379
      MCP_PORT: 8080
      ENVIRONMENT: development
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./.env:/app/.env
    # Override user for local development (allows file editing)
    user: "0:0"

volumes:
  postgres_data:
  redis_data:
