"""Add button configuration fields to signup forms

Revision ID: 1a0c426a5532
Revises: 94182d3ada51
Create Date: 2025-09-09 21:16:57.032518

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a0c426a5532"
down_revision: Union[str, Sequence[str], None] = "94182d3ada51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "form_fields",
        "field_type",
        existing_type=postgresql.ENUM(
            "text", "number", "select", "checkbox", name="fieldtype"
        ),
        nullable=True,
    )
    op.drop_index(op.f("ix_registrations_form_id"), table_name="registrations")
    op.add_column(
        "signup_forms",
        sa.Column(
            "button_type", sa.String(), nullable=False, server_default="single_submit"
        ),
    )
    op.add_column(
        "signup_forms",
        sa.Column(
            "primary_button_text",
            sa.String(),
            nullable=False,
            server_default="Register",
        ),
    )
    op.add_column(
        "signup_forms", sa.Column("secondary_button_text", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signup_forms", "secondary_button_text")
    op.drop_column("signup_forms", "primary_button_text")
    op.drop_column("signup_forms", "button_type")
    op.create_index(
        op.f("ix_registrations_form_id"), "registrations", ["form_id"], unique=False
    )
    op.alter_column(
        "form_fields",
        "field_type",
        existing_type=postgresql.ENUM(
            "text", "number", "select", "checkbox", name="fieldtype"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
