"""add cascade delete to form_fields foreign key

Revision ID: 32b86e3e1ca5
Revises: 57bcb9f61a92
Create Date: 2025-09-08 19:19:18.833537

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32b86e3e1ca5"
down_revision: Union[str, Sequence[str], None] = "57bcb9f61a92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("form_fields_form_id_fkey"), "form_fields", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "form_fields", "signup_forms", ["form_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "form_fields", type_="foreignkey")
    op.create_foreign_key(
        op.f("form_fields_form_id_fkey"),
        "form_fields",
        "signup_forms",
        ["form_id"],
        ["id"],
    )
    # ### end Alembic commands ###
