"""add form_fields table for custom form fields

Revision ID: 57bcb9f61a92
Revises: 7f62cfa084f2
Create Date: 2025-09-08 19:08:27.891526

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57bcb9f61a92"
down_revision: Union[str, Sequence[str], None] = "7f62cfa084f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_fields",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("field_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("placeholder", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("field_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["signup_forms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_form_fields_field_name"), "form_fields", ["field_name"], unique=False
    )
    op.create_index(
        op.f("ix_form_fields_form_id"), "form_fields", ["form_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_form_fields_form_id"), table_name="form_fields")
    op.drop_index(op.f("ix_form_fields_field_name"), table_name="form_fields")
    op.drop_table("form_fields")
    # ### end Alembic commands ###
