"""Add indexes to signup_form url_slug, is_active, and event_date fields

Revision ID: db918af13044
Revises: df788cd36e9a
Create Date: 2025-07-19 11:44:27.145232

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db918af13044"
down_revision: Union[str, Sequence[str], None] = "df788cd36e9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("signup_forms_url_slug_key"), "signup_forms", type_="unique"
    )
    op.create_index(
        op.f("ix_signup_forms_event_date"), "signup_forms", ["event_date"], unique=False
    )
    op.create_index(
        op.f("ix_signup_forms_is_active"), "signup_forms", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_signup_forms_url_slug"), "signup_forms", ["url_slug"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signup_forms_url_slug"), table_name="signup_forms")
    op.drop_index(op.f("ix_signup_forms_is_active"), table_name="signup_forms")
    op.drop_index(op.f("ix_signup_forms_event_date"), table_name="signup_forms")
    op.create_unique_constraint(
        op.f("signup_forms_url_slug_key"),
        "signup_forms",
        ["url_slug"],
    )
    # ### end Alembic commands ###
