name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    # Deploy to staging ONLY on pull requests
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Deploy to Railway Staging
      run: railway up --detach --service ez-scheduler-staging
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_STAGING }}
      working-directory: ./server

  deploy-production:
    runs-on: ubuntu-latest
    # Only deploy to production when code is merged to main branch
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Deploy to Railway Production (TEMPORARILY DISABLED)
      run: echo "Production deployment temporarily disabled. Staging deployment completed successfully."
      # Uncomment the lines below when ready to enable production deployment:
      # run: railway up --detach --service ez-scheduler-production
      # env:
      #   RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PRODUCTION }}
      # working-directory: ./server
